### ISSUE TITLE
关于问题#124

### ISSUE THREAD

**Issue by liminghe-li** [williamfzc/stagesepx#125]
请问下必须用0.13.1版本吗？我装了最新的0.14.0，但是这个问题仍然没有解决
https://github.com/williamfzc/stagesepx/issues/124

**Comment by liminghe-li** [comment]
还是说我需要重新训练模型？那数据集呢？不需要重新分拣吧？

**Comment by williamfzc** [comment]
可以直接 reopen #124，统一在那边讨论吧
