### ISSUE TITLE
怎么保留所有数据呢？

### ISSUE THREAD

**Issue by liminghe-li** [williamfzc/stagesepx#126]
我们在使用的时候发现产生数据集的时候，其中一部分帧会被直接删除，但是我们想保留所有帧，应该怎么做呢？

**Comment by williamfzc** [comment]
所有指什么，整个视频的所有帧？

**Comment by liminghe-li** [comment]
> 所有指什么，整个视频的所有帧？

是的，整个视频所有的帧

**Comment by williamfzc** [comment]
https://github.com/williamfzc/stagesepx/blob/43c8bc685e96c0796912aba49c5dca48e98e01c2/stagesepx/hook.py#L197

加上这个hook，关于怎么使用hook例子里有

**Comment by liminghe-li** [comment]
> https://github.com/williamfzc/stagesepx/blob/43c8bc685e96c0796912aba49c5dca48e98e01c2/stagesepx/hook.py#L197
> 
> 加上这个hook，关于怎么使用hook例子里有

好的感谢~

**Comment by liminghe-li** [comment]
我用所有的数据拆分成数据集0-8，训练出模型来后，去load_model的时候发现结果和我分拣的数据集不一样，少了几个文件夹，是get_range方法的参数不对吗?

**Comment by williamfzc** [comment]
> 我用所有的数据拆分成数据集0-8，训练出模型来后，去load_model的时候发现结果和我分拣的数据集不一样，少了几个文件夹，是get_range方法的参数不对吗?

切分跟分类这两块是分开的，训练集没问题分类应该就没什么问题；
少了几个文件夹是什么意思

**Comment by liminghe-li** [comment]
> > 我用所有的数据拆分成数据集0-8，训练出模型来后，去load_model的时候发现结果和我分拣的数据集不一样，少了几个文件夹，是get_range方法的参数不对吗?
> 
> 切分跟分类这两块是分开的，训练集没问题分类应该就没什么问题；
> 少了几个文件夹是什么意思

比如训练集是0-8，但是我训练出的结果的x_axis是['-3', '0', '1', '3', '5', '6', '7', '8']

**Comment by liminghe-li** [comment]
> > > 我用所有的数据拆分成数据集0-8，训练出模型来后，去load_model的时候发现结果和我分拣的数据集不一样，少了几个文件夹，是get_range方法的参数不对吗?
> > 
> > 
> > 切分跟分类这两块是分开的，训练集没问题分类应该就没什么问题；
> > 少了几个文件夹是什么意思
> 
> 比如训练集是0-8，但是我训练出的结果的x_axis是['-3', '0', '1', '3', '5', '6', '7', '8']

但是实际上1和4才是我想要的节点

**Comment by williamfzc** [comment]
这说明没有找到4
