### ISSUE TITLE
请问下get_range方法的threshold参数可以设置threshold=1吗？

### ISSUE THREAD

**Issue by liminghe-li** [williamfzc/stagesepx#128]
请问下get_range方法的threshold参数可以设置threshold=1吗？
我们目前遇到的问题是，我们测试淘宝的启动时间，但是做模型的视频和测试视频并不是同一个手机录制的，然后在load_model的时候，我们发现初始阶段的一些帧被放置在了我们设置的结束的stage里面
![image](https://user-images.githubusercontent.com/54129529/87498832-5c543e00-c68b-11ea-8f14-f5f5d88fdcf5.png)

**Comment by williamfzc** [comment]
get_range 的 threshold 主要用于判定稳态与非稳态，并不会影响分类结果；
这种问题还是模型问题，可能是训练集选取有误导致的，还是看场景，可以私发或贴一下；

**Comment by liminghe-li** [comment]
> get_range 的 threshold 主要用于判定稳态与非稳态，并不会影响分类结果；
> 这种问题还是模型问题，可能是训练集选取有误导致的，还是看场景，可以私发或贴一下；

那我qq联系一下您~
