### ISSUE TITLE
录像视频RuntimeError(f"frame {frame_id} not found in video")

### ISSUE THREAD

**Issue by jikeswife** [williamfzc/stagesepx#141]
使用一只手机对另一只手机的app启动进行录像，在 数据（图片）采集 阶段，运行cut.py脚本，报错
 File "C:\Users\Programs\Python\Python37\lib\site-packages\stagesepx\cutter\cut_result.py", line 32, in get_target_range_by_id
    raise RuntimeError(f"frame {frame_id} not found in video")
RuntimeError: frame 1 not found in video

而如果app启动视频是录屏得到的，则不会报错

**Comment by williamfzc** [comment]
视频经过 ffmpeg 处理了吗

**Comment by jikeswife** [comment]
> 视频经过 ffmpeg 处理了吗

博主你好，我有看你的文章，推荐的录制视频方式 1.软件录制+ffmpeg 2.外置摄像机 ，这个意思不就是外置摄像机就不用经过ffmpeg处理了吗，我有想去安装ffmepg，但网上的有关于windows上的ffmepg下载都是在 http://ffmpeg.zeranoe.com/builds/ 这个网站下载，但是这个网站应该是最近关闭了，而在官网下载的安装包还没有什么资料显示是如何安装的，所有暂时没有办法安装ffmpeg。work_with_stagesepx-master文件夹下的videos文件夹里的几个视频，应该都是经过了ffmepg处理的吧，不知为何也是有一些会报frame_id not found in video的错，比如short.mp4,douyin2.mp4,douyin3.mp4.

**Comment by williamfzc** [comment]
- stagesepx 版本多少？
- 还是建议先过 ffmpeg 看看问题是否还存在

或者私聊下 178894043

**Comment by jikeswife** [comment]
感谢博主，经过ffmpeg处理就不报错了，看来都得经过ffmpeg处理

**Comment by jikeswife** [comment]
感谢博主，经过ffmpeg处理就不报错了，看来都得经过ffmpeg处理

**Comment by jikeswife** [comment]
感谢博主，经过ffmpeg处理就不报错了，看来都得经过ffmpeg处理
