### ISSUE TITLE
WARNING:tensorflow:Your input ran out of data; interrupting training.

### ISSUE THREAD

**Issue by williamfzc** [williamfzc/stagesepx#145]
Make sure t hat your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 30 batches). You may need to use the repeat() function when b uilding your dataset.

**Comment by Supercool-p** [comment]
这个是训练集少了会出现这个提示诶

**Comment by williamfzc** [comment]
> 这个是训练集少了会出现这个提示诶

是，现在的默认值似乎有些问题

**Comment by williamfzc** [comment]
https://stackoverflow.com/questions/59864408/tensorflowyour-input-ran-out-of-data
https://github.com/tensorflow/tensorflow/issues/25254

after tensorflow 2.1
