### ISSUE TITLE
当训练集只包含一个文件夹时最好抛出warning

### ISSUE THREAD

**Issue by jikeswife** [williamfzc/stagesepx#146]
1.keras分类出来的结果只有两个类，本来应该有4个(参数为0.2 0.97 0 8)

2.运行中会报cudart not found，训练结果不正确是否与此有关，看了下CUDA是神经网络的加速器，理论上好像不会影响结果正确与否

下面附上训练集与预测结果
第一类
![IMG_20201028_162835](https://user-images.githubusercontent.com/23066575/97411530-5bde6b00-193b-11eb-93df-e1fa314e6310.jpg)
第二类
![IMG_20201028_162854](https://user-images.githubusercontent.com/23066575/97411569-68fb5a00-193b-11eb-9f15-cd474fc4c654.jpg)
第三类
![IMG_20201028_162904](https://user-images.githubusercontent.com/23066575/97411623-7a446680-193b-11eb-9b69-3bca6fe8aa48.jpg)
第四类
![IMG_20201028_162914](https://user-images.githubusercontent.com/23066575/97411655-84fefb80-193b-11eb-9be6-45523fed8b0d.jpg)

预测结果
![IMG_20201028_162746](https://user-images.githubusercontent.com/23066575/97411854-c4c5e300-193b-11eb-82b6-c1efd331b577.jpg)

运行时报的一些warning error 
![IMG_20201028_162946](https://user-images.githubusercontent.com/23066575/97411776-af50b900-193b-11eb-82d9-b685f12aea36.jpg)

**Comment by williamfzc** [comment]
![image](https://user-images.githubusercontent.com/13421694/97412353-6d744280-193c-11eb-87e7-f806709e9e37.png)

看起来是路径错了，只找到一类

**Comment by jikeswife** [comment]
![IMG_20201028_165740](https://user-images.githubusercontent.com/23066575/97414513-099f4900-193f-11eb-975c-e3eb4c21e004.jpg)
博主说的是这里的路径吗

**Comment by williamfzc** [comment]
训练集的路径有点问题，我估计是里面多了个子目录之类的

**Comment by jikeswife** [comment]
确实是有子目录，现在可以了，感谢😊
