### ISSUE TITLE
请教关于人工分拣的问题

### ISSUE THREAD

**Issue by liminghe-li** [williamfzc/stagesepx#149]
hi，博主您好
我在试用stagesepx的时候遇到了一些问题，比如分析APP启动时间的时候，最后稳定的页面发生变化的时候，就识别不到结束点了，我是需要每次都把新的结束页面放进分拣好的数据集吗？

**Comment by williamfzc** [comment]
是的，用这种方法提高模型的分辨能力，后面会越来越好就不用一直放了；
发生大的变化建议重新选训练集；

**Comment by liminghe-li** [comment]
> 是的，用这种方法提高模型的分辨能力，后面会越来越好就不用一直放了；
> 发生大的变化建议重新选训练集；

好的，非常感谢~
