### ISSUE TITLE
CropHook没有正确工作

### ISSUE THREAD

**Issue by mmjdm** [williamfzc/stagesepx#151]
1、我在cutter添加了CropHook
cutter = VideoCutter(compress_rate=1)
 ignore_hook = CropHook(size=(0.2, 1), offset=(0.8, 0))
cutter.add_hook(ignore_hook)
 res = cutter.cut(video, block=2, )
2、通过日志看，除了CompressHook、GreyHook，也有执行CropHook，但是没有正确裁剪数据
’11111111 (960, 1200) (0, 576)‘的日志：目标是裁剪出图片最下面的底tab范围
’22222222‘开头的元数据没问题
’333333333‘开头的日志可以看到：数组都变成了0
’444444444‘开头的：数据大小没变
![image](https://user-images.githubusercontent.com/22932888/106460976-1a77d180-64cf-11eb-955b-e98e95efd4ea.png)
3、这是我自己临时的方法
 print('333333333', frame.data[height_range[0]:height_range[1], width_range[0]:width_range[1]].shape)
 print('444444444', frame.data[height_range[0]:height_range[1], width_range[0]:width_range[1]])
![image](https://user-images.githubusercontent.com/22932888/106461609-f668c000-64cf-11eb-92f3-fc1d4a0df3c3.png)

**Comment by williamfzc** [comment]
听起来是正常的，目前的hook只会将无关的部分涂黑（=0），对于shape是没影响的

**Comment by mmjdm** [comment]
> 听起来是正常的，目前的hook只会将无关的部分涂黑（=0），对于shape是没影响的
> 是否我哪里有文档忘更新？
