### ISSUE TITLE
CropHook没有正确工作问题

### ISSUE THREAD

**Issue by mmjdm** [williamfzc/stagesepx#153]
刚才那个问题不小心删了
具体原因：因为我只想分析下面这部分
<img width="502" alt="image" src="https://user-images.githubusercontent.com/22932888/106466927-ec968b00-64d6-11eb-82f7-c5cc8ab08bea.png">
所以这种情况height_range, width_range = (960, 1200) (0, 576)
frame.data[: height_range[0]] = 0
frame.data[height_range[1] :] = 0
上面这两行没问题，正常把(960, 1200)之外的数据改成0
frame.data[: width_range[0]] = 0：这行没实际意思
frame.data[width_range[1] :] = 0：因为width_range[1]=576，小于height_range[0]，所以又把(960, 1200)这个范围内数据都改成了0
结果就是：所以数据都改成了0

**Comment by williamfzc** [comment]
明白，可以看看上面的修改是否有效
https://github.com/williamfzc/stagesepx/commit/72d47df5df0d3a54a80f8f13f2d5d7aa80fdbe56

**Comment by mmjdm** [comment]
嗯，修好了
