### ISSUE TITLE
您好，模型测试跟实际数帧工具测试差别较大，帮忙看一下需要修改哪个参数

### ISSUE THREAD

**Issue by mayan90** [williamfzc/stagesepx#172]
人工     stagesepx
3254  1090
3212   818
3229   1236
3275  1343
3205  1275
行为：例如调起键盘：点击输入框抬手到键盘完全展示，需要修改哪个参数？目前fps=240|threshold=0.97| offset=1

**Comment by williamfzc** [comment]
https://blog.csdn.net/wsc106/article/details/107351675
