### ISSUE TITLE
macbook M系列兼容性

### ISSUE THREAD

**Issue by as45045781** [williamfzc/stagesepx#181]
目前苹果M1上stagesepx要求py版本<3.8，但是如果项目中又有tensorflow-macos要求>=3.8以上版本 这样就会导致没办法使用了....

**Comment by williamfzc** [comment]
没有要求 <3.8 呀，目前写的是 ![PyPI - Python Version](https://img.shields.io/pypi/pyversions/stagesepx)   
有报错信息吗

**Comment by as45045781** [comment]
![{703EDAF3-3A87-38BD-684C-48B8B8503EEF}](https://user-images.githubusercontent.com/42176680/182346639-917679c3-282d-4f3d-bdc5-2a841b5f94dd.jpg)

**Comment by as45045781** [comment]
![{03212F89-783E-BD1E-E98F-F0018135CD49}](https://user-images.githubusercontent.com/42176680/182346805-152c9901-5beb-4cfb-aa3a-e33ce6240f3b.jpg)
有的呀

**Comment by williamfzc** [comment]
stagesepx 本体是可以到3.9的，sepmachine 只是随手做的 sample 没注意维护了，你可以：

- 直接用 stagesepx
- clone sepmachine 然后自己在本地随便改

**Comment by as45045781** [comment]
stagesepx的话我实验了一些版本，发现只有在3.8.10版本才可以安装成功！ 3.8.12/3.8.13 都会失败 更别说3.9了

**Comment by williamfzc** [comment]
也是在macbook M1？
我们的CI是 3.6-3.9 的：https://github.com/williamfzc/stagesepx/blob/master/.github/workflows/smoketest.yml

**Comment by as45045781** [comment]
是的没错，我机器是m1 pro
看来目前m1机器上3.8.10是最兼容的版本了

**Comment by williamfzc** [comment]
> stagesepx的话我实验了一些版本，发现只有在3.8.10版本才可以安装成功！ 3.8.12/3.8.13 都会失败 更别说3.9了

这个方便贴下报错不？看看这次是什么依赖有问题

**Comment by as45045781** [comment]
![{E388B1A3-0BD5-8533-BD66-B1FA0F509A1E}](https://user-images.githubusercontent.com/42176680/183553936-ae20b803-a4fa-41a7-aa9b-fa2772b8320f.jpg)
好像是opencv？

**Comment by williamfzc** [comment]
估计跟 #178 是一样的，这个问题还有待验证，等我找到一台M1试试

**Comment by williamfzc** [comment]
@as45045781 
可参考 #178 末尾提到的方式在M1上试跑，修复了时间戳未对齐功能

**Comment by williamfzc** [comment]
0.18.0 修复，详见 #178
