### ISSUE TITLE
report中报告和图片怎么设置成彩色图片，而不是灰色图片

### ISSUE THREAD

**Issue by linyajun558** [williamfzc/stagesepx#184]
**report中报告和图片怎么设置成彩色图片，而不是灰色图片**

**Comment by williamfzc** [comment]
图像处理一般都会用灰度图，所以暂时不额外支持彩色图。
实际使用上灰度图也够用了，有什么特殊场景吗？

**Comment by linyajun558** [comment]
就是领导觉得灰度图不美观，想用彩色图。。。。

**Comment by williamfzc** [comment]
如果要实现这个，需要在 https://github.com/williamfzc/stagesepx/blob/master/stagesepx/reporter.py 里：

- 图片数据往html上贴时；
- 从视频中抓彩色帧，替换掉原来的灰度图；
