### ISSUE TITLE
关于轮播图（走马灯）

### ISSUE THREAD

**Issue by williamfzc** [williamfzc/stagesepx#55]
轮播图 / 走马灯 的 概念：https://element.eleme.cn/#/zh-CN/component/carousel

很多人有疑问，认为轮播图不应该被分为多个状态，即便上面的图片发生了改变。

半自动场景下（人工触发+人工看报告），其实轮播图被检测为多个阶段无伤大雅，甚至更好。无论你希望看哪个阶段的数据，你都可以直接计算出来。后面着重讨论的是全自动化的场景。

轮播图这个概念是业务相关的，不会也不适合在该项目中做特定适配。很可能有人的场景就是检测轮播图切换速度。目前对于这种场景有两种解决方案：

- 手动新增样本
    - 如果你希望抹平轮播图之间的区别，你可以将处在不同轮播图状态的页面手动分到一个类别中再进行训练。当然，你可能需要更多的该类型图片来达到一个理想的效果
    - 如此做之后，这些轮播图将会被分到同一个类别中
    - 如何训练请参考 [这个例子](https://github.com/williamfzc/stagesepx/tree/master/example)
- 帧预处理
    - 截取非轮播图的部分进行判断 #53
    - 屏蔽掉轮播图的区域 #56

**Comment by turnsgreen** [comment]
对图像处理不是很熟悉，想求教一下，屏蔽和裁剪这两种方式，对测算结果会有不同影响吗？还是说两者跑出来的结果其实是一样的？

**Comment by williamfzc** [comment]
肯定有，否则也不需要这俩东西了。
