### ISSUE TITLE
报告简化

### ISSUE THREAD

**Issue by williamfzc** [williamfzc/stagesepx#75]
在很多场景下，用户（我们自己也是）实际上用得最多的功能是变化过程。

![image](https://user-images.githubusercontent.com/13421694/69228228-2b843d80-0bbe-11ea-91e0-4af34db49afc.png)

而基于此功能，已经能够满足大多数的需要，这让在它上面的稳定状态图示显得有些鸡肋。这个部分最好整合成为一个针对整个过程的描述，而不是分成两个部分。

目前因为两个部分的存在，新用户反而不知道如何提取自己需要的信息。

**Comment by williamfzc** [comment]
<img width="963" alt="截屏2019-11-21上午12 24 50" src="https://user-images.githubusercontent.com/13421694/69257072-65246b00-0bf5-11ea-8556-f8c3034b9e24.png">

新版本的结果会将变化过程与稳定过程合并

**Comment by williamfzc** [comment]
报告中加入视频信息

**Comment by williamfzc** [comment]
0.11+ 的版本有新的设计

![image](https://user-images.githubusercontent.com/13421694/75640645-b5897b00-5c70-11ea-9693-e9fb85355fc9.png)

以上图为例，时间是这么划分的：

- 1开始 - 142帧结束；
- 143开始 - 150帧结束；

所以可以看到，142帧的时间戳与143帧相同。

**Comment by williamfzc** [comment]
![image](https://user-images.githubusercontent.com/13421694/75648794-22f6d500-5c8c-11ea-9787-39bea094d583.png)

除此之外，你可以发现所有的 unstable range 都会比提示的多一帧。此处的设计是为了让阅读衔接更自然。
unstable range 的最后一帧实质上是下一个 stable range 的状态，这样能够将两个 stable range 彻底连接起来也不会有断层。

**Comment by CiaraCai** [comment]
> ![image](https://user-images.githubusercontent.com/13421694/75648794-22f6d500-5c8c-11ea-9787-39bea094d583.png)
> 
> 除此之外，你可以发现所有的 unstable range 都会比提示的多一帧。此处的设计是为了让阅读衔接更自然。
> unstable range 的最后一帧实质上是下一个 stable range 的状态，这样能够将两个 stable range 彻底连接起来也不会有断层。

因为unstable range都会有一张下个stable range的截图，我们在手动分类训练集的时候，是否应该将这张stable range的截图去掉呢？我自己这边是去掉这张截图的，因为担心两个range之前有相同图片作为训练集造成混淆，但是也就有了两个range之前的断层情况，想问一下你们在手动分类训练集的时候也是这样处理的嘛？

**Comment by williamfzc** [comment]
@CiaraCai 
- 报告展示的效果 跟 训练集 是两回事，他们之间没什么直接关系；
- 变化过程（unstable range）是不作为一个特定阶段放入训练集的，断层这个概念由 cutter 自动处理，只需要关心 stable 的东西，所以也不存在两个range有相同图片的情况；
